services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    env_file: .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  api:
    build: ./api
    container_name: flask-api
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
